# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

laplace <- function(x) {
    .Call('_StatComp20057_laplace', PACKAGE = 'StatComp20057', x)
}

MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20057_MetropolisC', PACKAGE = 'StatComp20057', sigma, x0, N)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_StatComp20057_gibbsC', PACKAGE = 'StatComp20057', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param age the first predictor (numeric)
#' @param female the second predictor (logical)
#' @param ily the third predictor (logical)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' res <- vaccC(age,female,ily)
#' }
#' @export
vaccC <- function(age, female, ily) {
    .Call('_StatComp20057_vaccC', PACKAGE = 'StatComp20057', age, female, ily)
}

